language: python
python:
  - "3.6"
notifications:
    email: false

install:
  - pip install coverage
  - pip install -r requirements.txt
script:
  - python -m unittest test_linearmodel.py
  - coverage run --source=./linearmodel/ test_linearmodel.py
  - coverage report
after_success:
  - coveralls
  