language: python
python:
  - "3.6"
notifications:
    email: false

install:
  - pip install coverage
  - pip install -r requirements.txt
script:
  - coverage run --source=./linearmodel/ --omit=./linearmodel/gui/* test_linearmodel.py
  - coverage report
after_success:
  - coveralls
  